### ISSUE TITLE
vdso-offsets.h

### ISSUE THREAD

**Issue by olrak2** [olrak2/android_kernel_huawei_hi6210sft#1]
I need to make self a file called vdso-offsets.h with the value: #define vdso_offset_sigtramp 0x04e0

command: 
> echo "#define vdso_offset_sigtramp 0x04e0" > include/generated/vdso-offsets.h

The kernel itself makes a empty file so if somebody knows a solution feel free to share.

**Comment by ksrt12** [comment]
you just need to change the permissions, e.g mode change 100644 => 100755 arch/arm64/kernel/vdso/gen_vdso_offsets.sh

**Comment by olrak2** [comment]
@ksrt12 : thanks it did work.

I did a find 
> /home/ubuntu/android/cm121/vendor/huawei -type f -exec chmod 775 {} \; 
but apparently it did not the job.
